name: durpalla
description: A new Flutter project for Jolzan app design.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  printing: ^5.11.0
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.2
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_native_splash:
  color: "#003366"             # deep ocean background
  image: assets/logo-white.png # your logo
  android_12:
    color: "#003366"
    image: assets/logo-white.png
